def vocabularytest():

    print("Vocabulary Test")
    AClassmateName=input("Enter your ClassmateName: ")
    Verbing=input("Enter Verbing: ")
    RoominaHouse=input("Enter a room: ")
    Bodypart=input("Enter a Bodypart: ")
    Adjective=input("Enter an Adjective: ")
    AnAdjective=input("enter and Adjective: ")
    ABodypart=input("Enter a Body Part: ")
    Colour=input("Enter a Colour: ")
    Verb=input("Enter a Verb: ")
    Holiday=input("Enter a Holiday: ")
    Adjective3=input("Enter an Adjective: ")
    Drink=input("Enter a Drink: ")
    Food=input("Enter a Food: ")
    PsimpleWords=input("Enter a Past Simple Words: ")
    Adjective4=input("Enter an adjective: ")
    Colour2=input("Enter a Colour: ")
    ItemofClothing=input("Enter An Item of clothing")
    Verb2=input("Input a verb: ")
    AdayoftheWeek=input("Enter a Day of the Week: ")
    Animal=input("Enter an animal: ")
    EnterName=input("Enter your Name: ")

    print("A Love Letter")
    print("My love", AClassmateName)
    print("Last night i had a dream. You and i were", Verbing)
    print("(together in the", RoominaHouse)
    print("with our", Bodypart)
    print("touching. It was so romantic")
    print("You are so", Adjective)
    print("and", AnAdjective)
    print("that everytime i think of you my")
    print("turns", Colour)
    print("and i", Verb)
    print("I Still remember that wonderful time we spent together last", Holiday)
    print("We went to a very", Adjective3)
    print("restaurant and we drink so much", Drink)
    print("and also so much", Food)
    print("that we", PsimpleWords)
    print("After dinner you gave me that",Adjective4, Colour2, ItemofClothing)
    print("Sometime whe I miss you I put it on and I", Verb2)
    print("Ill see you next", AdayoftheWeek)
    print("Sweetheart!")
    print("All my love,")
    print("Your", Animal, EnterName)

    
    print()

    main()