L1 =["Sam", 102, "USA"]
L2 = [11, 20, 3, 47, 55, 96]
color = ["red", "blue", "green"]
list2 = [1,2,3,4]

list2.append(100)
L1.insert(1, "mabingnay")
print(list2)
print(color)
color[0] = "pink"
color[-1] = "orange"
print(color)
print(L1)
print(L2)