size = int(input("Enter the size of the list: "))

# Create an empty list
userlist = []

# Get input values for the list
for i in range(size):
    value = (input("Enter a value for index {}: ".format(i)))
    userlist.append(value)

# Print the initial list
print("Initial list:", userlist)

# Modify the list
while True:
    print("\nWhat do you want to do?")
    print("1. Change a value")
    print("2. Remove an element")
    print("3. Exit")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        j = int(input("Enter the index of the value to change: "))
        if j < 0 or j >= size:
            print("Invalid index!")
            continue
        newlist = (input("Enter the new value: "))
        userlist[j] = newlist
        print("Modified list:", userlist)
    elif choice == 2:
        j = int(input("Enter the index of the element to remove: "))
        if j < 0 or j >= size:
            print("Invalid index!")
            continue
        userlist.pop(j)
        size -= 1
        print("Modified list:", userlist)
    elif choice == 3:
        # Exit the program
        print("Done")
        break
    else:
        print("Invalid choice!")

 